### ISSUE TITLE
OCaml 5.2 support

### ISSUE THREAD

**Issue by kit-ty-kate** [dariusf/ppx_interact#2]
This package fails to build on OCaml 5.2 with:
```
#=== ERROR while compiling ppx_interact.0.1.0 =================================#
# context              2.2.0~beta2~dev | linux/x86_64 | ocaml-variants.5.2.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.2/.opam-switch/build/ppx_interact.0.1.0
# command              ~/.opam/5.2/bin/dune build -p ppx_interact -j 1 @install
# exit-code            1
# env-file             ~/.opam/log/ppx_interact-20-12799c.env
# output-file          ~/.opam/log/ppx_interact-20-12799c.out
### output ###
# (cd _build/default && /home/opam/.opam/5.2/bin/ocamlc.opt -w -40 -g -bin-annot -I runtime/.ppx_interact_runtime.objs/byte -I /home/opam/.opam/5.2/lib/linenoise -I /home/opam/.opam/5.2/lib/ocaml/compiler-libs -I /home/opam/.opam/5.2/lib/ocaml/unix -no-alias-deps -o runtime/.ppx_interact_runtime.objs/byte/ppx_interact_runtime.cmo -c -impl runtime/ppx_interact_runtime.ml)
# File "runtime/ppx_interact_runtime.ml", line 215, characters 8-31:
# 215 |     try Misc.find_in_path_uncap search_path (unit ^ ".cmt")
#               ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value "Misc.find_in_path_uncap"
```

**Comment by dariusf** [comment]
Thanks! I've fixed it. Will make a new release soon.
